 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My timelines';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('timeline', array('action'=>'add'));?>">Add new timeline</a>
 </p>

 <table class="table">
 <tr>
     <th>Start Date</th>
     <th>End Date</th>
     <th>headline</th>
     <th>Text</th>
     <th>Media</th>
     <th>Media Credit</th>
     <th>Media Caption</th>
     <th>Media Thumbnail</th>
     <th>Type</th>
     <th>Tag ID</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($timelines as $timeline) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($timeline->start_date);?></td>
     <td><?php echo $this->escapeHtml($timeline->end_date);?></td>
     <td><?php echo $this->escapeHtml($timeline->headline);?></td>
     <td><?php echo $this->escapeHtml($timeline->text);?></td>
     <td><?php echo $this->escapeHtml($timeline->media);?></td>
     <td><?php echo $this->escapeHtml($timeline->media_credit);?></td>
     <td><?php echo $this->escapeHtml($timeline->media_caption);?></td>
     <td><?php echo $this->escapeHtml($timeline->media_thumbnail);?></td>
     <td><?php echo $this->escapeHtml($timeline->type);?></td>
     <td><?php echo $this->escapeHtml($timeline->tag_id_tag);?></td>
     <td>
         <a href="<?php echo $this->url('timeline',
             array('action'=>'edit', 'id' => $timeline->id_timeline));?>">Edit</a>
         <a href="<?php echo $this->url('timeline',
             array('action'=>'delete', 'id' => $timeline->id_timeline));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>