 <?php
 // module/Album/view/album/album/index.phtml:

 $title = 'My timelines';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('timeline', array('action'=>'add'));?>">Add new timeline</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Artist</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($timelines as $timeline) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($timeline->title);?></td>
     <td><?php echo $this->escapeHtml($timeline->artist);?></td>
     <td>
         <a href="<?php echo $this->url('album',
             array('action'=>'edit', 'id_timeline' => $timeline->id_timeline));?>">Edit</a>
         <a href="<?php echo $this->url('album',
             array('action'=>'delete', 'id_timeline' => $timeline->id_timeline));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>